### ISSUE TITLE
Add a method for the gateway to manage the "chattiness" of the nodes

### ISSUE THREAD

**Issue by chipmc** [chipmc/SeeInsights-LoRA-Node#6]
This could be with a command that would limit the frequency of occupancy updates form the nodes.  For example, if 10 people enter a room, that could generate 10 updates.  However, during peak hours, the gateway may need to limit node updates to 30 seconds or a minute.  In this scenario, the gateway would send an alert code with a data acknowledgement to limit how offend updates are send which would result in fewer updates - perhaps going from occupancy of 1 to 5 to 10 if a class is starting in one room.

**Comment by orbitllc** [comment]
"Chattiness" definition:
- How often does a node send an update to the gateway
- How often does a Gateway send an update to Ubidots 

Story: 
As a Node, I must transmit less than once per minute, even if the counts change, so that I can reduce collisions and save battery life. 

Tasks: 
Use data acknowledgement report from the gateway to change the node's reporting frequency
- how chatty is it

**Comment by chipmc** [comment]
For the node, the following changes: 

Chip
- [ ] - Update data payload for a data report acknowledgement
- [ ] - [ ] - Add Chattiness setting
- [ ] - [ ] - Add correct net occupancy
- [ ] - [ ] - Open / close and cleaning 
- [ ] - [ ] - Array to store space setting

- [ ] - Add alert to trigger calibration (or bundle into Join) - for unconfigured node

Alex 
- [ ] - Remove black hair - enhanced calibration with config variables
- [ ] - Modify SPADs / Centers to reflect different installations configuration bits
- [ ] - Power Savings
- [ ] - [ ] - Deep sleep
- [ ] - [ ]  - Enable pin on the TOF sensor
- [ ] - [ ]  - Reduce time to go back to sleep after not detection

**Comment by orbitllc** [comment]
Have these issues been resolved or acknowledged in other issues?

**Comment by chipmc** [comment]
Yes, I believe they are.
